### ISSUE TITLE
🐛 [버그] - 새로운 Sekai 등록 도중 이전 버튼으로 돌아갈시 최초 화면 다음 버튼 비활성화

### ISSUE THREAD

**Issue by imnyang** [Plus-Platforms/plusIssueTracker#1]
### 버그 설명

스샷 올리다 죽을듯
![IMG_5831](https://github.com/Plus-Platforms/plusIssueTracker/assets/72956792/46cb461e-e9b8-4513-abda-b50dc351056a)

### 재현 과정

```bash
1. Sekai 등록을 한다
2. 다음을 누른다
3. 이전을 누르면 짜잔 비활성화
```

### 스크린샷

```bash
설명 참조
```

### 플랫폼

웹사이트 (Safari 계열)

### 유해성

잘못된 표시

**Comment by 10kwon** [comment]
인지하고있음
